# Informaci칩n del sitio
title: "Fernando Torralba - Data Scientist"
email: fernandoptorralba@gmail.com
description: "Portfolio de proyectos de Ciencia de Datos y An치lisis de Datos"
baseurl: "/fernando.github.io" # El nombre de tu repositorio
url: "https://fernanditokitkatgr.github.io"
twitter_username: fernanditokitkatgr
github_username: fernanditokitkatgr

# Configuraci칩n del tema
theme: minima

# Plugins de Jekyll
plugins:
  - jekyll-feed

# Archivos y carpetas que no se procesar치n
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Opciones de Markdown
markdown: kramdown
